
function [P, f] = forward(x) 
%Implementation of forward algorithm according to same HMM as viterbi
%function. Implementation is similar to the latter, differing in that the
%dynamic programming matrix saves the forward probabilities instead and the path isn't saved. 
%P is the total probability of sequence x being generated by the HMM
%f is the dynamic programming matrix containing forward probabilities

%size of DNA sequence
N = length(x);

%number of states
Q=3;


%transition matrix

a=([0.6, 0.4, 0;
    0.25, 0.5, 0.25;
    0.25, 0.25, 0.5]);

%emission matrix
%columns correspond to nucleotides while rows correspond to hidden states

order='ATCG';

e=([0.4, 0.3, 0, 0.3;
    0.1, 0.1, 0.4, 0.4;
    0.4, 0.3, 0.3, 0]);


%initializing f matrix
f=zeros(Q,N);


f(:,1)=e(:, strfind(order,x(1))).*(1/Q);


%Recursive loop computing dynamic programming matrix according to forward
%algorithm's formula

for i=2:N
   current_n = strfind(order,x(i));
   for k=1:Q
        f(k,i)= e(k, current_n)*(f(:,i-1)'*a(:,k));
   end
   
end

%Total probability of x sequence being generated by the model is equal to 
%the sum of all entries of the last column
P=sum(f(:,N));


end